### PR TITLE
Made generateRequest method to provide all payment details

### PR DESCRIPTION
**Pull request by ravindranpandu**
Made the `HPP.generateRequest()` to return paymentURL as well as the entire `paymentData`, currently we get the payment data by using `url.query`, with this change we can get the `paymentData.merchantReferance` and more.

### CODE REVIEW

**Comment by onchainguy-btc** [comment]
@ravindranpandu thanks for submitting this PR. @hekike what do you think? If we would merge this we would have to do a major version update as this would break existing code. 

I think I would prefer an additional parameter for the callback so that existing code will still work.

**Comment by ravindranpandu** [comment]
@seb0zz i accept this will cause a regression for existing products using adyen-node, but rather than stripping out the data from url i felt this is much clean, thoughts?

**Comment by onchainguy-btc** [comment]
Yeah I get your point. In this case I would need access to the npm module for publishing a new version. @hekike could you give me access?

**Comment by hekike** [comment]
@seb0zz sure, what's your npm username?

**Comment by onchainguy-btc** [comment]
Username is [seb0zz](https://www.npmjs.com/~seb0zz)

**Comment by hekike** [comment]
@seb0zz done ;)

**Comment by onchainguy-btc** [comment]
@hekike thanks - pretty sure I can merge this with a new tag at the weekend @ravindranpandu

**Comment by ravindranpandu** [comment]
Thank you very much @seb0zz @hekike

**Pull request merged**
